### PR TITLE
<fix>VPC security port lookup for ranges

### PR DESCRIPTION
**Pull request by roleyfoley**
Adds support for port ranges in ingress security groups
Adds default policy to pipeline ec2 instances

### CODE REVIEW

**Comment by ml019** [comment]
Wonder if port ranges should be a separate object rather than a variant of a port. Lookup up could then use fallback to treat the port as an individual port and if not defined then look for a range.

**Comment by roleyfoley** [comment]
> Wonder if port ranges should be a separate object rather than a variant of a port. Lookup up could then use fallback to treat the port as an individual port and if not defined then look for a range.

Woudln't you then need to ensure that you don't have overlapping names between the port objects and the portrange objects to make sure fallback works?

**Comment by ml019** [comment]
You would - but when would you want to name a range the same as a port? Guess its whether they are really are the same or different concept.

Maybe we should be treating a single port as a port range of 1 - so change ports collection to a portranges collection...

**Comment by roleyfoley** [comment]
Yeah that could work. What this has is backwards compatability for single ports or port ranges. 
Ports are defined in config quite a bit so it would be a breaking change

**Comment by ml019** [comment]
Hmm. OK - I see why you went the way you did. Let's go with this as an interim solution. Can always add distinct portrange object later.

**Pull request merged**
