### PR TITLE
<refactor> Prepare for transition to v2.0.0 cmdb format

### PR DESCRIPTION
**Pull request by ml019**
Reorder the searches to favour the more common cmdb directory layouts.

Preference v2.0.0 as it will become the most common layout.

### CODE REVIEW

**Comment by roleyfoley** [comment]
Should this be part of the PR to enable the v2.0.0 upgrade rather than doing it before

**Comment by ml019** [comment]
@roleyfoley - ok I can reorder to reflect current structure for now and add reorder to PR to switch to v2.0.0

**Comment by ml019** [comment]
@roleyfoley tweaked things to permit parallel use of pre and post v2.0.0, with a favouring of pre v2.0.0 where possible. Ready for review

**Comment by roleyfoley** [comment]
Can this just be part of the PR to enable the v2 cutover? Feels like we are adding something we don't need yet

**Comment by ml019** [comment]
It is already added - this is just making it more optimised for current cmdb layout. Happy to repurpose this as the v2.0.0 upgrade PR.

**Comment by ml019** [comment]
New scope 

 Add a mechanism to separate the list of available CMDB upgrade and cleanup versions from the version targetted by default.

This supports a few scenarios;

 - selective upgrade or cleanup of cmdbs ahead of a change to the default targetted value
 - pinning of the upgrade or cleanup CMDB version.

Two new environment variables can be set to control this behaviour;

GENERATION_MAX_CMDB_UPGRADE_VERSION
GENERATION_MAX_CMDB_CLEANUP_VERSION

Add v2.0.0 to the list of available upgrades, and optimise context directory searches assuming v2.0.0 is the default.

**Pull request merged**
